version: '2'

services:
  nginxgqlsymphony:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BUILD_DATE: "2023-05-19"
    image: nginx:latest
    ports:
      - "8200:80"
      - "8444:443"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpgqlsymphony
    networks:
      - bf_frontend_gqlsymphony

  phpgqlsymphony:
    build: ./php
    volumes:
      - ../src:/var/www/html
    links:
      - mysqlgqlsymphony
    networks:
      - bf_frontend_gqlsymphony
      - bf_backend_gqlsymphony

  mysqlgqlsymphony:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "9018:3306"
    volumes:
      - ../docker/volumes/mariadb:/var/lib/mysql
    networks:
      - bf_backend_gqlsymphony
networks:
  bf_frontend_gqlsymphony:
  bf_backend_gqlsymphony:
