controllers:
    resource: ../src/Controller/
    type: attribute
graphql:
    path: '/graphql'
    controller: 'App\Controller\GraphQlController::index'
tools:
    path: '/gendbmodels'
    controller: 'App\Controller\ToolsController::generateModels'
